#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// scripts/sync-photos.js
//
// Syncs your Photo Work folder into the repo and generates src/data/photos.ts
//
// USAGE:  npm run sync-photos
//
// What it does:
//   1. Reads every subfolder (shoot) in your SOURCE_DIR
//   2. Resizes each image to max 1400px wide using macOS `sips` (no install needed)
//   3. Copies to public/images/photography/<shoot-slug>/
//   4. Writes src/data/photos.ts with all paths grouped by shoot
//
// Add new photos to your Photo Work folder, run the script, done.
// ─────────────────────────────────────────────────────────────────────────────

const fs   = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ── CONFIG — update SOURCE_DIR if your Photo Work folder moves ───────────────
const SOURCE_DIR  = path.join(require("os").homedir(), "Desktop", "Photo Work");
const DEST_DIR    = path.join(__dirname, "..", "public", "images", "photography");
const DATA_FILE   = path.join(__dirname, "..", "src", "data", "photos.ts");
const MAX_PX      = 1400;   // max width/height in pixels
const EXTENSIONS  = new Set([".jpg", ".jpeg", ".png", ".webp", ".JPG", ".JPEG", ".PNG", ".WEBP"]);
// ─────────────────────────────────────────────────────────────────────────────

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function isImage(file) {
  return EXTENSIONS.has(path.extname(file));
}

if (!fs.existsSync(SOURCE_DIR)) {
  console.error(`❌  Source folder not found: ${SOURCE_DIR}`);
  console.error(`    Update SOURCE_DIR in scripts/sync-photos.js`);
  process.exit(1);
}

fs.mkdirSync(DEST_DIR, { recursive: true });

const shoots = fs.readdirSync(SOURCE_DIR)
  .filter(name => fs.statSync(path.join(SOURCE_DIR, name)).isDirectory())
  .sort();

const photoData = [];
let totalCopied = 0;
let totalSkipped = 0;

for (const shoot of shoots) {
  const shootSrc  = path.join(SOURCE_DIR, shoot);
  const slug      = slugify(shoot);
  const shootDest = path.join(DEST_DIR, slug);
  fs.mkdirSync(shootDest, { recursive: true });

  const files = fs.readdirSync(shootSrc).filter(isImage).sort();
  const photos = [];

  for (const file of files) {
    const src  = path.join(shootSrc, file);
    const dest = path.join(shootDest, file.toLowerCase());
    const webPath = `/images/photography/${slug}/${file.toLowerCase()}`;

    if (fs.existsSync(dest)) {
      // Skip if dest is newer than src
      const srcMtime  = fs.statSync(src).mtimeMs;
      const destMtime = fs.statSync(dest).mtimeMs;
      if (destMtime >= srcMtime) {
        photos.push({ src: webPath, alt: shoot });
        totalSkipped++;
        continue;
      }
    }

    try {
      // Use macOS sips to resize — built-in, no extra packages
      execSync(`sips -Z ${MAX_PX} "${src}" --out "${dest}"`, { stdio: "pipe" });
      photos.push({ src: webPath, alt: shoot });
      totalCopied++;
      process.stdout.write(`  ✓ ${shoot}/${file}\n`);
    } catch (err) {
      // Fall back to plain copy if sips fails
      fs.copyFileSync(src, dest);
      photos.push({ src: webPath, alt: shoot });
      totalCopied++;
      process.stdout.write(`  → ${shoot}/${file} (copied, resize failed)\n`);
    }
  }

  if (photos.length > 0) {
    photoData.push({ shoot, slug, photos });
    console.log(`📁 ${shoot}: ${photos.length} photos`);
  }
}

// ── Write src/data/photos.ts ─────────────────────────────────────────────────
const tsContent = `// AUTO-GENERATED by scripts/sync-photos.js — do not edit manually
// Run \`npm run sync-photos\` to update

export type Photo = { src: string; alt: string };
export type Shoot = { shoot: string; slug: string; photos: Photo[] };

export const photoShoots: Shoot[] = ${JSON.stringify(photoData, null, 2)};

export const allPhotos: Photo[] = photoShoots.flatMap(s => s.photos);
`;

fs.writeFileSync(DATA_FILE, tsContent, "utf8");

console.log(`\n✅  Done! ${totalCopied} copied, ${totalSkipped} already up to date.`);
console.log(`📝  Updated src/data/photos.ts with ${photoData.length} shoots`);
console.log(`\n   Restart your dev server to see changes.\n`);
