// AUTO-GENERATED by scripts/sync-photos.js — do not edit manually
// Run `npm run sync-photos` to update

export type Photo = { src: string; alt: string };
export type Shoot = { shoot: string; slug: string; photos: Photo[] };

export const photoShoots: Shoot[] = [
  {
    "shoot": "August 2025 Edits",
    "slug": "august-2025-edits",
    "photos": [
      {
        "src": "/images/photography/august-2025-edits/img_2032.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2033.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2034.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2035.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2036.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2037.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2038.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2039.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2040.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2041.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2042.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2043.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2044.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2045.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2048.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2049.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2050.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2051.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2052.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2053.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2054.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2055.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2056.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2057.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2058.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2059.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2060.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2061.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2062.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2063.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2064.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2065.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2066.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2067.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2068.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2069.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2070.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2071.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2072.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2073.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2074.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2075.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2076.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2077.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2078.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2079.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2080.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2081.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2082.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2083.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2084.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2085.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2086.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2087.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2088.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2089.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2090.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2091.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2092.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2093.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2094.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2095.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2096.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2097.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2098.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2099.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2100.jpg",
        "alt": "August 2025 Edits"
      }
    ]
  },
  {
    "shoot": "Cullen",
    "slug": "cullen",
    "photos": [
      {
        "src": "/images/photography/cullen/img_1880.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1972-2.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1972.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973-2.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973-3.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973.jpg",
        "alt": "Cullen"
      }
    ]
  },
  {
    "shoot": "Kelsey",
    "slug": "kelsey",
    "photos": [
      {
        "src": "/images/photography/kelsey/img_1837.jpg",
        "alt": "Kelsey"
      },
      {
        "src": "/images/photography/kelsey/img_1861.jpg",
        "alt": "Kelsey"
      }
    ]
  },
  {
    "shoot": "Monicas Wedding",
    "slug": "monicas-wedding",
    "photos": [
      {
        "src": "/images/photography/monicas-wedding/img_2176.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2178.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2179.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2180.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2182.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2183.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2184.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2185.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2186.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2187.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2188.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2189.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2190.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2191.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2192.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2193.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2194.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2195.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2196.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2199.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2203.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2205.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2206.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2208.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2209.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2210.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2212.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2213.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2214.jpg",
        "alt": "Monicas Wedding"
      },
      {
        "src": "/images/photography/monicas-wedding/img_2217.jpg",
        "alt": "Monicas Wedding"
      }
    ]
  },
  {
    "shoot": "NOV 24 edit",
    "slug": "nov-24-edit",
    "photos": [
      {
        "src": "/images/photography/nov-24-edit/img_1868.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2020.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2021.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2022.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2023.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2024.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2026.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2027.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2028.jpg",
        "alt": "NOV 24 edit"
      }
    ]
  },
  {
    "shoot": "Nov 24",
    "slug": "nov-24",
    "photos": [
      {
        "src": "/images/photography/nov-24/img_1975.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1976.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1977.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1995.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1996.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1997.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1998.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1999.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2000.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2001.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2002.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2003.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2004.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2005.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2006.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2007.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2008.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2009.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2010.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2011.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2014.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2015.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2016.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2017.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2018.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2019.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2020.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2021.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2022.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2023.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2024.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2025.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2026.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2027.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2028.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2029.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2030.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2031.jpg",
        "alt": "Nov 24"
      }
    ]
  }
];

export const allPhotos: Photo[] = photoShoots.flatMap(s => s.photos);
