// AUTO-GENERATED by scripts/sync-photos.js — do not edit manually
// Run `npm run sync-photos` to update

export type Photo = { src: string; alt: string };
export type Shoot = { shoot: string; slug: string; photos: Photo[] };

export const photoShoots: Shoot[] = [
  {
    "shoot": "August 2025 Edits",
    "slug": "august-2025-edits",
    "photos": [
      {
        "src": "/images/photography/august-2025-edits/img_2032.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2033.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2034.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2044.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2045.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2048.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2049.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2050.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2051.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2053.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2054.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2055.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2056.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2057.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2058.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2059.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2060.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2069.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2070.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2077.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2078.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2079.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2080.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2081.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2082.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2083.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2084.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2085.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2086.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2087.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2088.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2089.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2090.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2091.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2093.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2094.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2095.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2096.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2097.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2098.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2099.jpg",
        "alt": "August 2025 Edits"
      },
      {
        "src": "/images/photography/august-2025-edits/img_2100.jpg",
        "alt": "August 2025 Edits"
      }
    ]
  },
  {
    "shoot": "Cullen",
    "slug": "cullen",
    "photos": [
      {
        "src": "/images/photography/cullen/img_1972-2.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1972.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973-2.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973-3.jpg",
        "alt": "Cullen"
      },
      {
        "src": "/images/photography/cullen/img_1973.jpg",
        "alt": "Cullen"
      }
    ]
  },
  {
    "shoot": "Kelsey",
    "slug": "kelsey",
    "photos": [
      {
        "src": "/images/photography/kelsey/img_1837.jpg",
        "alt": "Kelsey"
      }
    ]
  },
  {
    "shoot": "NOV 24 edit",
    "slug": "nov-24-edit",
    "photos": [
      {
        "src": "/images/photography/nov-24-edit/img_1868.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2020.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2021.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2022.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2023.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2024.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2026.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2027.jpg",
        "alt": "NOV 24 edit"
      },
      {
        "src": "/images/photography/nov-24-edit/img_2028.jpg",
        "alt": "NOV 24 edit"
      }
    ]
  },
  {
    "shoot": "Nov 24",
    "slug": "nov-24",
    "photos": [
      {
        "src": "/images/photography/nov-24/img_1975.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1976.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1977.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1996.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1997.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1998.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_1999.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2000.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2001.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2002.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2003.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2004.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2005.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2006.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2007.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2008.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2009.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2010.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2011.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2014.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2015.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2016.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2017.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2029.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2030.jpg",
        "alt": "Nov 24"
      },
      {
        "src": "/images/photography/nov-24/img_2031.jpg",
        "alt": "Nov 24"
      }
    ]
  }
];

export const allPhotos: Photo[] = photoShoots.flatMap(s => s.photos);
